// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "skymen_BetterOutline",
  name: "Better Outline",
  version: "2.0.0.0",
  category:
    // "blend",
    // "distortion",
    // "normal-mapping",
    // "tiling",
    "other",
  // "color",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "A better outline addon",
  supportedRenderers: ["webgl", "webgl2", "webgpu"],
  blendsBackground: false,
  usesDepth: false,
  crossSampling: true,
  preservesOpaqueness: false,
  animated: false,
  mustPredraw: true,
  extendBox: {
    horizontal: 50,
    vertical: 50,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "color",
      id: "color",
      value: [0, 0, 0],
      uniform: "outlinecolor",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Color",
      desc: "The color of the outline",
    },
    {
      type: "float",
      id: "width",
      value: 1,
      uniform: "width",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Width",
      desc: "The width of the outline",
    },
    {
      type: "float",
      id: "precision-step",
      value: 1,
      uniform: "precisionStep",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Precision Step",
      desc: "The step in pixels between each sub outline the shader will render",
    },
    {
      type: "float",
      id: "samples",
      value: 16,
      uniform: "samples",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Samples",
      desc: "The number of angles the outline will render at",
    },
  ],
};
